var_1: &job_defaults
  environment:
    IMAGE_NAME: ngqt/qode
  docker:
    - image: circleci/buildpack-deps:stretch

var_2: &build_image
  run:
    name: Build Docker image
    command: docker build -t $IMAGE_NAME:latest .

version: 2.1

executors:
  docker-publisher:
    <<: *job_defaults

jobs:
  validate:
    <<: *job_defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Shellcheck
          command: |
            sudo apt-get update
            sudo apt-get install shellcheck
            shellcheck *.sh
      - run:
          name: Hadolint
          command: docker run --rm -i hadolint/hadolint < Dockerfile

  build:
    <<: *job_defaults
    steps:
      - checkout
      - setup_remote_docker
      - *build_image

  build-tag:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - *build_image
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build:
    jobs:
      - validate
      - build:
          requires:
            - validate
  build-publish-tag:
    jobs:
      - validate:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - validate
      - publish-tag:
          requires:
            - build-tag
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/